package:
  name: pyfk
  version: "0.3.1"

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - numpy >=1.21
    - scipy >=1.7
    - obspy >=1.3
    - cysignals >=1.11.2
    - cython >=0.29.28
  run:
    - python >=3.7,<3.10
    - numpy >=1.21
    - scipy >=1.7
    - obspy >=1.3
    - cysignals >=1.11.2
test:
  requires:
    - pytest
    - pytest-mpi
  imports:
    - pyfk

about:
  home: https://github.com/ziyixi/pyfk
  license: Apache-2.0
  license_file: LICENSE
  summary: Pyfk is the python version of FK used to calculate the Green's function and the synthetic waveforms for the 1D Earth model.