name: Publish Conda Package

on: 
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: ziyixi/conda-publish-action@master
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}
        platforms: 'ubuntu-latest'