name: sphinx
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install pipenv and run doc
        run: |
          pip install pipenv
          pipenv --python=`which python` install -d --skip-lock
          pipenv run python setup.py develop
          export VENV_HOME_DIR=$(pipenv --venv)
          source $VENV_HOME_DIR/bin/activate
          cd docs
          make html
          cd ..
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
