name: sphinx
on:
  push:
    branches:
      - master
jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: run doc
        run: |
          pip install poetry-core@https://github.com/python-poetry/poetry-core/archive/refs/tags/1.1.0a7.zip
          pip install numpy obspy cython scipy cysignals
          pip install . --no-build-isolation
          pip install sphinx==4.5 pydata-sphinx-theme sphinx-autoapi jupyter-sphinx sphinx-copybutton pytest
          cd docs
          make html
          echo "pyfk.ziyixi.science" > _build/CNAME
          cd ..
      - name: push to github page
        if: ${{ !env.ACT }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
