name: pyfk
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.6", "3.7", "3.8"]
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install openmp on mac
        if: matrix.os == 'macos-latest'
        run: |
          brew install open-mpi

      - name: Install openmp on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install openmpi-bin libopenmpi-dev -y

      - name: Install pipenv and packages
        run: |
          pip install pipenv
          pipenv --python=`which python` install -d
          export VENV_HOME_DIR=$(pipenv --venv)
          source $VENV_HOME_DIR/bin/activate

      - name: Generate coverage report
        run: |
          pipenv install .
          mkdir coverage_test
          cd coverage_test
          coverage run --source=pyfk -m pytest --pyargs pyfk
          coverage xml
          cd ..
          mv coverage_test/coverage.xml .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          env_vars: OS
          fail_ci_if_error: false
          verbose: true

      - name: Test MPI run
        run: |
          export PYFK_USE_MPI=1
          pipenv uninstall pyfk
          pipenv install mpi4py
          pipenv install .
          cd coverage_test
          mpirun --oversubscribe -np 1 pytest --with-mpi --pyargs pyfk
          mpirun --oversubscribe -np 3 pytest --with-mpi --pyargs pyfk
          cd ..