name: test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.7", "3.8", "3.9"]
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install openmp on mac
        if: matrix.os == 'macos-latest'
        run: |
          brew install open-mpi

      - name: Install openmp on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install openmpi-bin libopenmpi-dev -y

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Generate coverage report
        run: |
          pip install .
          pip install coverage pytest pytest-mpi
          mkdir coverage_test
          cd coverage_test
          coverage run --source=pyfk -m pytest --pyargs pyfk
          coverage xml
          cd ..
          mv coverage_test/coverage.xml .

      - name: Upload coverage to Codecov
        if: ${{ !env.ACT }}
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          env_vars: OS
          fail_ci_if_error: false
          verbose: true

      - name: Test MPI run
        run: |
          pip uninstall pyfk -y
          PYFK_USE_MPI=1 pip install ".[mpi]"
          cd coverage_test
          export OMPI_ALLOW_RUN_AS_ROOT=1
          export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1
          mpirun --oversubscribe -np 1 pytest --with-mpi --pyargs pyfk
          mpirun --oversubscribe -np 3 pytest --with-mpi --pyargs pyfk
          cd ..