name: pyfk
on:
  push:
    branches:
      - master
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.6", "3.7", "3.8"]
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install openmp on mac
        if: matrix.os == 'macos-latest'
        run: |
          brew install open-mpi

      - name: Install openmp on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install openmpi-bin libopenmpi-dev -y

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install pipenv packages
        run: |
          pipenv install -d --skip-lock
          pipenv graph

      - name: Generate coverage report
        run: |
          pipenv run pip install .
          mkdir coverage_test
          cd coverage_test
          pipenv run coverage run --source=pyfk -m pytest --pyargs pyfk
          pipenv run coverage xml
          cd ..
          mv coverage_test/coverage.xml .

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          env_vars: OS
          fail_ci_if_error: false
          verbose: true

      - name: Test MPI run
        run: |
          export PYFK_USE_MPI=1
          pipenv run pip uninstall pyfk -y
          pipenv run pipenv install mpi4py
          pipenv run pip install .
          cd coverage_test
          pipenv run mpirun --oversubscribe -np 1 pytest --with-mpi --pyargs pyfk
          pipenv run mpirun --oversubscribe -np 3 pytest --with-mpi --pyargs pyfk
          cd ..